function(CheckLibrary)
    if (APPLE)
        find_library(HAVE_CURL curl)
        if(HAVE_CURL)
            include_directories(/usr/local/opt/curl/include)
            link_directories(/usr/local/opt/curl/lib)
        else()
            message(WARNING "install curl by homebrew is better")
        endif()

    elseif(UNIX)
        include_directories(/usr/include)
        link_directories(/usr/lib /usr/lib/x86_64-linux-gnu)

    endif (APPLE)
endfunction()

function(LinTargetLibrary Target)
    if(APPLE)
        target_link_libraries(${Target} OpenCL curl)
    elseif(UNIX)
        target_link_libraries(${Target} OpenCL curl)
    endif()
endfunction()
